service: frontend

provider:
  name: aws
  region: us-east-1 # Choose your preferred AWS region

plugins:
  - serverless-finch # This plugin is used to deploy static websites

custom:
  client:
    bucketName: makalu-frontend
    distributionFolder: build # The folder where your build static files are
    indexDocument: index.html
    errorDocument: index.html

package:
  individually: true
  exclude:
    - node_modules/**
    - source/**

functions: {}

resources:
  Resources:
    MakaluFrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.client.bucketName}
        WebsiteConfiguration:
          RoutingRules:
            - RoutingRule:
                Condition:
                  HttpErrorCodeReturnedEquals: "404"
                Redirect:
                  HttpRedirectCode: "200"
                  Protocol: "http"
                  ReplaceKeyPrefixWith: "#!/"
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["PUT", "POST", "DELETE"]
              AllowedOrigins: ["https://7pvpeztz21.execute-api.us-east-1.amazonaws.com"]
              MaxAgeSeconds: 3000
            - AllowedHeaders: ["*"]
              AllowedMethods: ["GET"]
              AllowedOrigins: ["*"]
              MaxAgeSeconds: 3000

