
service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    DB_HOST: groupdb.cxihxkjcod9w.us-east-1.rds.amazonaws.com 
    DB_USER: adminDB 
    DB_PASSWORD: AD#CS509
    DB_NAME: consignment 

functions:
  app:
    handler: handler.server
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
    vpc:
      securityGroupIds:
        - sg-0dcd396a0440dd091
      subnetIds:
        - subnet-07906e38adaa5584b
        - subnet-0caea60a84e35cfd6
        - subnet-096337045e4e29952
        - subnet-02cfbab578f6ef115 
        - subnet-09f8aa91f27f654c9 
        - subnet-06b77cb5c9c45233a 

